WINDOW_HEIGHT = 720
WINDOW_WIDTH = 1080

CARDS_WIDE = 4
CARD_SIZE_FACTOR = 0.25

BOARD_MARGIN = 100 * 2
BOARD_VIRTUAL_WIDTH = WINDOW_WIDTH - BOARD_MARGIN
BOARD_VIRTUAL_HEIGHT = WINDOW_HEIGHT - BOARD_MARGIN

BOARD_START_X = BOARD_MARGIN / 2
BOARD_START_Y = BOARD_MARGIN / 2