gCards = {
    ['clubs-1']  = love.graphics.newImage('resources/images/ace_of_clubs.png'),
    ['clubs-2']  = love.graphics.newImage('resources/images/2_of_clubs.png'),
    ['clubs-3']  = love.graphics.newImage('resources/images/3_of_clubs.png'),
    ['clubs-4']  = love.graphics.newImage('resources/images/4_of_clubs.png'),
    ['clubs-5']  = love.graphics.newImage('resources/images/5_of_clubs.png'),
    ['clubs-6']  = love.graphics.newImage('resources/images/6_of_clubs.png'),
    ['clubs-7']  = love.graphics.newImage('resources/images/7_of_clubs.png'),
    ['clubs-8']  = love.graphics.newImage('resources/images/8_of_clubs.png'),
    ['clubs-9']  = love.graphics.newImage('resources/images/9_of_clubs.png'),
    ['clubs-10'] = love.graphics.newImage('resources/images/10_of_clubs.png'),
    ['clubs-11'] = love.graphics.newImage('resources/images/jack_of_clubs.png'),
    ['clubs-12'] = love.graphics.newImage('resources/images/queen_of_clubs.png'),
    ['clubs-13'] = love.graphics.newImage('resources/images/king_of_clubs.png'),

    ['diamonds-1']  = love.graphics.newImage('resources/images/ace_of_diamonds.png'),
    ['diamonds-2']  = love.graphics.newImage('resources/images/2_of_diamonds.png'),
    ['diamonds-3']  = love.graphics.newImage('resources/images/3_of_diamonds.png'),
    ['diamonds-4']  = love.graphics.newImage('resources/images/4_of_diamonds.png'),
    ['diamonds-5']  = love.graphics.newImage('resources/images/5_of_diamonds.png'),
    ['diamonds-6']  = love.graphics.newImage('resources/images/6_of_diamonds.png'),
    ['diamonds-7']  = love.graphics.newImage('resources/images/7_of_diamonds.png'),
    ['diamonds-8']  = love.graphics.newImage('resources/images/8_of_diamonds.png'),
    ['diamonds-9']  = love.graphics.newImage('resources/images/9_of_diamonds.png'),
    ['diamonds-10'] = love.graphics.newImage('resources/images/10_of_diamonds.png'),
    ['diamonds-11'] = love.graphics.newImage('resources/images/jack_of_diamonds.png'),
    ['diamonds-12'] = love.graphics.newImage('resources/images/queen_of_diamonds.png'),
    ['diamonds-13'] = love.graphics.newImage('resources/images/king_of_diamonds.png'),

    ['hearts-1']  = love.graphics.newImage('resources/images/ace_of_hearts.png'),
    ['hearts-2']  = love.graphics.newImage('resources/images/2_of_hearts.png'),
    ['hearts-3']  = love.graphics.newImage('resources/images/3_of_hearts.png'),
    ['hearts-4']  = love.graphics.newImage('resources/images/4_of_hearts.png'),
    ['hearts-5']  = love.graphics.newImage('resources/images/5_of_hearts.png'),
    ['hearts-6']  = love.graphics.newImage('resources/images/6_of_hearts.png'),
    ['hearts-7']  = love.graphics.newImage('resources/images/7_of_hearts.png'),
    ['hearts-8']  = love.graphics.newImage('resources/images/8_of_hearts.png'),
    ['hearts-9']  = love.graphics.newImage('resources/images/9_of_hearts.png'),
    ['hearts-10'] = love.graphics.newImage('resources/images/10_of_hearts.png'),
    ['hearts-11'] = love.graphics.newImage('resources/images/jack_of_hearts.png'),
    ['hearts-12'] = love.graphics.newImage('resources/images/queen_of_hearts.png'),
    ['hearts-13'] = love.graphics.newImage('resources/images/king_of_hearts.png'),

    ['spades-1']  = love.graphics.newImage('resources/images/ace_of_spades.png'),
    ['spades-2']  = love.graphics.newImage('resources/images/2_of_spades.png'),
    ['spades-3']  = love.graphics.newImage('resources/images/3_of_spades.png'),
    ['spades-4']  = love.graphics.newImage('resources/images/4_of_spades.png'),
    ['spades-5']  = love.graphics.newImage('resources/images/5_of_spades.png'),
    ['spades-6']  = love.graphics.newImage('resources/images/6_of_spades.png'),
    ['spades-7']  = love.graphics.newImage('resources/images/7_of_spades.png'),
    ['spades-8']  = love.graphics.newImage('resources/images/8_of_spades.png'),
    ['spades-9']  = love.graphics.newImage('resources/images/9_of_spades.png'),
    ['spades-10'] = love.graphics.newImage('resources/images/10_of_spades.png'),
    ['spades-11'] = love.graphics.newImage('resources/images/jack_of_spades.png'),
    ['spades-12'] = love.graphics.newImage('resources/images/queen_of_spades.png'),
    ['spades-13'] = love.graphics.newImage('resources/images/king_of_spades.png'),

    ['backside'] = love.graphics.newImage('resources/images/back_orange.png')
}


gFonts = {
    ['score'] = love.graphics.newFont('resources/fonts/score.ttf', 20),
    ['message'] = love.graphics.newFont('resources/fonts/score.ttf', 30)
}